// Package LifeService comment
// This file was generated by tars2go 1.1.4
// Generated from ServerStatus.tars
package LifeService

import (
	"fmt"

	"github.com/TarsCloud/TarsGo/tars/protocol/codec"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = fmt.Errorf
var _ = codec.FromInt8

type ErrorCode int32

const (
	ErrorCode_SUCCESS          = 200
	ErrorCode_USEREXIST        = 301001
	ErrorCode_PHONEEXIST       = 301002
	ErrorCode_CLUBEXIST        = 301003
	ErrorCode_MANAGEREXIST     = 301004
	ErrorCode_USERAPPLIED      = 301005
	ErrorCode_ACTIVITYEXIST    = 301006
	ErrorCode_RECORDEXIST      = 301007
	ErrorCode_USERNOTEXIST     = 404001
	ErrorCode_CLUBNOTEXIST     = 404002
	ErrorCode_MANAGERNOTEXIST  = 404003
	ErrorCode_ACTIVITYNOTEXIST = 404004
	ErrorCode_APPLYNOTEXIST    = 404005
	ErrorCode_RECORDNOTEXIST   = 404006
	ErrorCode_SERVERERROR      = 500
)
